sudo: required
services:
  - docker

before_install:
  - docker build -t ashtonferns/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ashtonferns/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "docker-react"
  env: DockerReact-env
  bucket_name: "elasticbeanstalk-ca-central-1-683912229208"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY