sudo: required
services:
  - docker

before_install:
  - docker build -t ashtonferns/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ashtonferns/docker-react npm run test -- --coverage